apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shynet-cert
  namespace: default
spec:
  secretName: shynet-secret
  commonName: fqdn
  dnsNames:
  - fqdn
  issuerRef:
    name: REPLACEME
    kind: ClusterIssuer