apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shynet-cert
  namespace: default
spec:
  secretName: shynet-secret
  commonName: fqdn
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - fqdn
  issuerRef:
    name: REPLACEME
    kind: ClusterIssuer