apiVersion: v1
kind: Secret
metadata:
    name: shynet-settings
type: Opaque
stringData:
    # Django settings
    DEBUG: "False"
    ALLOWED_HOSTS: fqdn # For better security, set this to your deployment's domain. Comma separated.
    DJANGO_SECRET_KEY: django-secret-key
    ACCOUNT_SIGNUPS_ENABLED: "False"
    TIME_ZONE: "America/New_York"

    # Redis configuration (if you use the default Kubernetes config, this will work)
    REDIS_CACHE_LOCATION: "redis://shynet-redis.default.svc.cluster.local/0"
    CELERY_BROKER_URL: "redis://shynet-redis.default.svc.cluster.local/1"

    # PostgreSQL settings
    DB_NAME: "shynet"
    DB_USER: postgres-db-user
    DB_PASSWORD: postgres-db-password
    DB_HOST: "postgresql-service:5432"

    # Email settings
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
    EMAIL_HOST: ""
    SERVER_EMAIL: "Shynet <noreply@shynet.example.com>"